name: Determine Release Type
description: |
  This action determines the release type (major, minor, patch) based on PR labels.
inputs: {}
outputs:
  type:
    description: |
      The release type determined from PR labels (major, minor, patch).
    value: ${{ steps.determine_release_type.outputs.type }}
runs:
  using: 'composite'
  steps:
    - name: Determine release type
      id: determine_release_type
      shell: bash
      run: |
        if [[ -n "$bump" && ("$bump" == "major" || "$bump" == "minor" || "$bump" == "patch") ]]; then
          echo "Release type: ${{ github.event.inputs.bump }}"
          echo "type=${{ github.event.inputs.bump }}" >> $GITHUB_OUTPUT
          exit 0
        fi

        if echo "${{ toJson(github.event.pull_request.labels) }}" | grep -q 'release-type/major'; then
          echo "Release type: major"
          echo "type=major" >> $GITHUB_OUTPUT
          exit 0
        fi

        if echo "${{ toJson(github.event.pull_request.labels) }}" | grep -q 'release-type/minor'; then
          echo "Release type: minor"
          echo "type=minor" >> $GITHUB_OUTPUT
          exit 0
        fi

        if echo "${{ toJson(github.event.pull_request.labels) }}" | grep -q 'release-type/patch'; then
          echo "Release type: patch"
          echo "type=patch" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "No release-type label found."
        exit 1
